baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'PHP-TUI'

[markup.tableOfContents]
  startLevel = 1

[markup.goldmark.renderer]
unsafe=true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'
